# Generated by Django 3.2.7 on 2021-11-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiengkho', models.CharField(max_length=100, null=True)),
                ('phienamtiengkho', models.CharField(max_length=100, null=True)),
                ('fileaudiotiengkho', models.FileField(null=True, upload_to='audio')),
                ('vidutiengkho', models.CharField(max_length=200, null=True)),
                ('tiengviet', models.CharField(max_length=100, null=True)),
                ('phienamtiengviet', models.CharField(max_length=100, null=True)),
                ('fileaudiotiengviet', models.FileField(null=True, upload_to='audio')),
                ('vidutiengviet', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'dictionary',
            },
        ),
    ]
