# Generated by Django 3.2.7 on 2021-12-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20211206_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='fileaudiotiengkho',
            field=models.FileField(null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='fileaudiotiengviet',
            field=models.FileField(null=True, upload_to='audio'),
        ),
    ]
