# Generated by Django 3.2.7 on 2021-12-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20211206_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='fileaudiotiengkho',
            field=models.FileField(default='', null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='fileaudiotiengviet',
            field=models.FileField(default='', null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='phienamtiengkho',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='phienamtiengviet',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='tiengviet',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='vidutiengkho',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='vidutiengviet',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
