# Generated by Django 3.2.7 on 2021-11-19 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_chepbai_chepbai_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoiVaTraLoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cauhoitiengkho', models.TextField(null=True)),
                ('cauhoitiengviet', models.TextField(null=True)),
                ('traloitiengkho', models.TextField(null=True)),
                ('traloitiengviet', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('idbai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
            options={
                'db_table': 'courses_whquestion',
            },
        ),
    ]
