# Generated by Django 3.2.7 on 2021-11-19 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_tuvung'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tuvung',
            table='courses_tuvung',
        ),
        migrations.CreateModel(
            name='DatCau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tu', models.CharField(max_length=50, null=True)),
                ('tiengkho', models.CharField(max_length=50, null=True)),
                ('tiengviet', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('idbai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
            options={
                'db_table': 'courses_datcau',
            },
        ),
    ]
